// Classification name mapping utility
// Maps technical classification names to friendly display names

const classificationMap: Record<string, string> = {
  'MICROSOFT.BASE.CLASSIFICATION': 'Base Classification',
  'MICROSOFT.FINANCIAL.AUSTRALIA.BANK_ACCOUNT_NUMBER': 'Australia Bank Account Number',
  'MICROSOFT.FINANCIAL.CANADA.BANK_ACCOUNT_NUMBER': 'Canada Bank Account Number',
  'MICROSOFT.FINANCIAL.CREDIT_CARD_NUMBER': 'Credit Card Number',
  'MICROSOFT.FINANCIAL.EU_DEBIT_CARD': 'EU Debit Card',
  'MICROSOFT.FINANCIAL.INTERNATIONAL.BANK_ACCOUNT_NUMBER': 'International Bank Account Number (IBAN)',
  'MICROSOFT.FINANCIAL.ISRAEL.BANK_ACCOUNT_NUMBER': 'Israel Bank Account Number',
  'MICROSOFT.FINANCIAL.ITALY.FISCAL.CODE': 'Italy Fiscal Code',
  'MICROSOFT.FINANCIAL.JAPAN.BANK_ACCOUNT_NUMBER': 'Japan Bank Account Number',
  'MICROSOFT.FINANCIAL.NEW.ZEALAND.BANK.ACCOUNT.NUMBER': 'New Zealand Bank Account Number',
  'MICROSOFT.FINANCIAL.SWIFT_CODE': 'SWIFT Code',
  'MICROSOFT.FINANCIAL.US.ABA_ROUTING_NUMBER': 'US ABA Routing Number',
  'MICROSOFT.FINANCIAL.US.BANK_ACCOUNT_NUMBER': 'US Bank Account Number',
  'MICROSOFT.GOVERNMENT.ARGENTINA.DNI_NUMBER': 'Argentina DNI Number',
  'MICROSOFT.GOVERNMENT.AUSTRALIA.BUSINESS.NUMBER': 'Australia Business Number',
  'MICROSOFT.GOVERNMENT.AUSTRALIA.COMPANY.NUMBER': 'Australia Company Number',
  'MICROSOFT.GOVERNMENT.AUSTRALIA.DRIVERS_LICENSE_NUMBER': 'Australia Driver\'s License',
  'MICROSOFT.GOVERNMENT.AUSTRALIA.MEDICAL_ACCOUNT_NUMBER': 'Australia Medical Account Number',
  'MICROSOFT.GOVERNMENT.AUSTRALIA.PASSPORT_NUMBER': 'Australia Passport Number',
  'MICROSOFT.GOVERNMENT.AUSTRALIA.TAX_FILE_NUMBER': 'Australia Tax File Number',
  'MICROSOFT.GOVERNMENT.AUSTRIA.DRIVERS.LICENSE.NUMBER': 'Austria Driver\'s License',
  'MICROSOFT.GOVERNMENT.AUSTRIA.IDENTITY.CARD': 'Austria Identity Card',
  'MICROSOFT.GOVERNMENT.AUSTRIA.PASSPORT.NUMBER': 'Austria Passport Number',
  'MICROSOFT.GOVERNMENT.AUSTRIA.SOCIAL.SECURITY.NUMBER': 'Austria Social Security Number',
  'MICROSOFT.GOVERNMENT.AUSTRIA.TAX.IDENTIFICATION.NUMBER': 'Austria Tax ID',
  'MICROSOFT.GOVERNMENT.AUSTRIA.VALUE.ADDED.TAX': 'Austria VAT Number',
  'MICROSOFT.GOVERNMENT.BELGIUM.DRIVERS.LICENSE.NUMBER': 'Belgium Driver\'s License',
  'MICROSOFT.GOVERNMENT.BELGIUM.NATIONAL_NUMBER': 'Belgium National Number',
  'MICROSOFT.GOVERNMENT.BELGIUM.PASSPORT.NUMBER': 'Belgium Passport Number',
  'MICROSOFT.GOVERNMENT.BELGIUM.VALUE.ADDED.TAX.NUMBER': 'Belgium VAT Number',
  'MICROSOFT.GOVERNMENT.BRAZIL.CPF_NUMBER': 'Brazil CPF Number',
  'MICROSOFT.GOVERNMENT.BRAZIL.LEGAL_IDENTITY_ID_CARD': 'Brazil Legal Identity Card (RG)',
  'MICROSOFT.GOVERNMENT.BRAZIL.NATIONAL_ID_CARD': 'Brazil National ID Card (CNH)',
  'MICROSOFT.GOVERNMENT.BULGARIA.DRIVERS.LICENSE.NUMBER': 'Bulgaria Driver\'s License',
  'MICROSOFT.GOVERNMENT.BULGARIA.PASSPORT.NUMBER': 'Bulgaria Passport Number',
  'MICROSOFT.GOVERNMENT.BULGARIA.UNIFORM.CIVIL.NUMBER': 'Bulgaria Uniform Civil Number',
  'MICROSOFT.GOVERNMENT.CANADA.DRIVERS_LICENSE_NUMBER': 'Canada Driver\'s License',
  'MICROSOFT.GOVERNMENT.CANADA.HEALTH_SERVICE_NUMBER': 'Canada Health Service Number',
  'MICROSOFT.GOVERNMENT.CANADA.PASSPORT_NUMBER': 'Canada Passport Number',
  'MICROSOFT.GOVERNMENT.CANADA.PERSONAL_HEALTH_IDENTIFICATION_NUMBER': 'Canada Personal Health ID (PHIN)',
  'MICROSOFT.GOVERNMENT.CANADA.SOCIAL_INSURANCE_NUMBER': 'Canada Social Insurance Number',
  'MICROSOFT.GOVERNMENT.CHILE.CDI_NUMBER': 'Chile Identity Card Number (CDI)',
  'MICROSOFT.GOVERNMENT.CHINA.RESIDENT_IDENTITY_CARD_NUMBER': 'China Resident Identity Card',
  'MICROSOFT.GOVERNMENT.CITY_NAME': 'City Name',
  'MICROSOFT.GOVERNMENT.COUNTRY_NAME': 'Country Name',
  'MICROSOFT.GOVERNMENT.CROATIA.DRIVERS.LICENSE.NUMBER': 'Croatia Driver\'s License',
  'MICROSOFT.GOVERNMENT.CROATIA.ID_CARD_NUMBER': 'Croatia Identity Card Number',
  'MICROSOFT.GOVERNMENT.CROATIA.PASSPORT.NUMBER': 'Croatia Passport Number',
  'MICROSOFT.GOVERNMENT.CROATIA.PERSONAL_IDENTIFICATION_NUMBER': 'Croatia Personal ID (OIB)',
  'MICROSOFT.GOVERNMENT.CYPRUS.DRIVERS.LICENSE.NUMBER': 'Cyprus Driver\'s License',
  'MICROSOFT.GOVERNMENT.CYPRUS.IDENTITY.CARD': 'Cyprus Identity Card',
  'MICROSOFT.GOVERNMENT.CYPRUS.PASSPORT.NUMBER': 'Cyprus Passport Number',
  'MICROSOFT.GOVERNMENT.CYPRUS.TAX.IDENTIFICATION.NUMBER': 'Cyprus Tax ID',
  'MICROSOFT.GOVERNMENT.CZECH.NATIONAL_ID_CARD_NUMBER': 'Czech National Identity Card',
  'MICROSOFT.GOVERNMENT.CZECH.REPUBLIC.DRIVERS.LICENSE.NUMBER': 'Czech Driver\'s License',
  'MICROSOFT.GOVERNMENT.CZECH.REPUBLIC.PASSPORT.NUMBER': 'Czech Passport Number',
  'MICROSOFT.GOVERNMENT.DENMARK.DRIVERS.LICENSE.NUMBER': 'Denmark Driver\'s License',
  'MICROSOFT.GOVERNMENT.DENMARK.PASSPORT.NUMBER': 'Denmark Passport Number',
  'MICROSOFT.GOVERNMENT.DENMARK.PERSONAL_ID_NUMBER': 'Denmark Personal ID (CPR)',
  'MICROSOFT.GOVERNMENT.ESTONIA.DRIVERS.LICENSE.NUMBER': 'Estonia Driver\'s License',
  'MICROSOFT.GOVERNMENT.ESTONIA.PASSPORT.NUMBER': 'Estonia Passport Number',
  'MICROSOFT.GOVERNMENT.ESTONIA.PERSONAL.IDENTIFICATION.CODE': 'Estonia Personal ID Code',
  'MICROSOFT.GOVERNMENT.EU.DRIVERS_LICENSE_NUMBER': 'EU Driver\'s License',
  'MICROSOFT.GOVERNMENT.EU.NATIONAL_IDENTIFICATION_NUMBER': 'EU National ID Number',
  'MICROSOFT.GOVERNMENT.EU.PASSPORT_NUMBER': 'EU Passport Number',
  'MICROSOFT.GOVERNMENT.EU.SOCIAL_SECURITY_NUMBER_OR_EQUIVALENT_ID': 'EU Social Security Number',
  'MICROSOFT.GOVERNMENT.EU.TAX_IDENTIFICATION_NUMBER': 'EU Tax ID (TIN)',
  'MICROSOFT.GOVERNMENT.FINLAND.DRIVERS.LICENSE.NUMBER': 'Finland Driver\'s License',
  'MICROSOFT.GOVERNMENT.FINLAND.EUROPEAN.HEALTH.INSURANCE.NUMBER': 'Finland European Health Insurance Number',
  'MICROSOFT.GOVERNMENT.FINLAND.NATIONAL_ID_NUMBER': 'Finland National ID',
  'MICROSOFT.GOVERNMENT.FINLAND.PASSPORT_NUMBER': 'Finland Passport Number',
  'MICROSOFT.GOVERNMENT.FRANCE.CNI': 'France National Identity Card (CNI)',
  'MICROSOFT.GOVERNMENT.FRANCE.DRIVERS_LICENSE_NUMBER': 'France Driver\'s License',
  'MICROSOFT.GOVERNMENT.FRANCE.HEALTH.INSURANCE.NUMBER': 'France Health Insurance Number',
  'MICROSOFT.GOVERNMENT.FRANCE.PASSPORT_NUMBER': 'France Passport Number',
  'MICROSOFT.GOVERNMENT.FRANCE.SOCIAL_SECURITY_NUMBER': 'France Social Security Number (INSEE)',
  'MICROSOFT.GOVERNMENT.FRANCE.TAX.IDENTIFICATION.NUMBER': 'France Tax ID',
  'MICROSOFT.GOVERNMENT.FRANCE.VALUE.ADDED.TAX.NUMBER': 'France VAT Number',
  'MICROSOFT.GOVERNMENT.GERMANY.DRIVERS_LICENSE_NUMBER': 'Germany Driver\'s License',
  'MICROSOFT.GOVERNMENT.GERMANY.ID_CARD_NUMBER': 'Germany Identity Card',
  'MICROSOFT.GOVERNMENT.GERMANY.PASSPORT_NUMBER': 'Germany Passport Number',
  'MICROSOFT.GOVERNMENT.GERMANY.TAX.IDENTIFICATION.NUMBER': 'Germany Tax ID',
  'MICROSOFT.GOVERNMENT.GERMANY.VALUE.ADDED.TAX.NUMBER': 'Germany VAT Number',
  'MICROSOFT.GOVERNMENT.GREECE.DRIVERS.LICENSE.NUMBER': 'Greece Driver\'s License',
  'MICROSOFT.GOVERNMENT.GREECE.ID_CARD_NUMBER': 'Greece Identity Card',
  'MICROSOFT.GOVERNMENT.GREECE.PASSPORT.NUMBER': 'Greece Passport Number',
  'MICROSOFT.GOVERNMENT.GREECE.SOCIAL.SECURITY.NUMBER': 'Greece Social Security Number (AMKA)',
  'MICROSOFT.GOVERNMENT.GREEK.TAX.IDENTIFICATION.NUMBER': 'Greece Tax ID (AFM)',
  'MICROSOFT.GOVERNMENT.HONGKONG.ID_CARD_NUMBER': 'Hong Kong Identity Card (HKID)',
  'MICROSOFT.GOVERNMENT.HUNGARIAN.SOCIAL.SECURITY.NUMBER': 'Hungary Social Security Number (TAJ)',
  'MICROSOFT.GOVERNMENT.HUNGARIAN.VALUE.ADDED.TAX.NUMBER': 'Hungary VAT Number',
  'MICROSOFT.GOVERNMENT.HUNGARY.DRIVERS.LICENSE.NUMBER': 'Hungary Driver\'s License',
  'MICROSOFT.GOVERNMENT.HUNGARY.PASSPORT.NUMBER': 'Hungary Passport Number',
  'MICROSOFT.GOVERNMENT.HUNGARY.PERSONAL.IDENTIFICATION.NUMBER': 'Hungary Personal ID',
  'MICROSOFT.GOVERNMENT.HUNGARY.TAX.IDENTIFICATION.NUMBER': 'Hungary Tax ID',
  'MICROSOFT.GOVERNMENT.INDIA.PAN_INDIVIDUAL': 'India Permanent Account Number (PAN)',
  'MICROSOFT.GOVERNMENT.INDIA.UNIQUE_IDENTIFCATION_NUMBER': 'India Aadhaar Number',
  'MICROSOFT.GOVERNMENT.INDONESIA.IDENTITY_CARD_NUMBER': 'Indonesia Identity Card (KTP)',
  'MICROSOFT.GOVERNMENT.IRELAND.DRIVERS.LICENSE.NUMBER': 'Ireland Driver\'s License',
  'MICROSOFT.GOVERNMENT.IRELAND.PASSPORT.NUMBER': 'Ireland Passport Number',
  'MICROSOFT.GOVERNMENT.IRELAND.PERSONAL_PUBLIC_SERVICE_NUMBER': 'Ireland Personal Public Service Number (PPS)',
  'MICROSOFT.GOVERNMENT.ISRAEL.NATIONAL_ID_NUMBER': 'Israel National ID',
  'MICROSOFT.GOVERNMENT.ITALY.DRIVERS_LICENSE_NUMBER': 'Italy Driver\'s License',
  'MICROSOFT.GOVERNMENT.ITALY.PASSPORT.NUMBER': 'Italy Passport Number',
  'MICROSOFT.GOVERNMENT.ITALY.VALUE.ADDED.TAX': 'Italy VAT Number',
  'MICROSOFT.GOVERNMENT.JAPAN.DRIVERS_LICENSE_NUMBER': 'Japan Driver\'s License',
  'MICROSOFT.GOVERNMENT.JAPAN.PASSPORT_NUMBER': 'Japan Passport Number',
  'MICROSOFT.GOVERNMENT.JAPAN.RESIDENCE_CARD_NUMBER': 'Japan Residence Card Number',
  'MICROSOFT.GOVERNMENT.JAPAN.RESIDENT_REGISTRATION_NUMBER': 'Japan Resident Registration Number',
  'MICROSOFT.GOVERNMENT.JAPAN.SOCIAL_INSURANCE_NUMBER': 'Japan Social Insurance Number',
  'MICROSOFT.GOVERNMENT.LATVIA.DRIVERS.LICENSE.NUMBER': 'Latvia Driver\'s License',
  'MICROSOFT.GOVERNMENT.LATVIA.PASSPORT.NUMBER': 'Latvia Passport Number',
  'MICROSOFT.GOVERNMENT.LATVIA.PERSONAL.CODE': 'Latvia Personal Code',
  'MICROSOFT.GOVERNMENT.LITHUANIA.DRIVERS.LICENSE.NUMBER': 'Lithuania Driver\'s License',
  'MICROSOFT.GOVERNMENT.LITHUANIA.PASSPORT.NUMBER': 'Lithuania Passport Number',
  'MICROSOFT.GOVERNMENT.LITHUANIA.PERSONAL.CODE': 'Lithuania Personal Code',
  'MICROSOFT.GOVERNMENT.LUXEMBOURG.DRIVERS.LICENSE.NUMBER': 'Luxembourg Driver\'s License',
  'MICROSOFT.GOVERNMENT.LUXEMBOURG.PASSPORT.NUMBER': 'Luxembourg Passport Number',
  'MICROSOFT.GOVERNMENT.LUXEMBURG.NATIONAL.IDENTIFICATION.NUMBER.NATURAL.PERSONS': 'Luxembourg National ID (Natural Persons)',
  'MICROSOFT.GOVERNMENT.LUXEMBURG.NATIONAL.IDENTIFICATION.NUMBER.NON.NATURAL.PERSONS': 'Luxembourg National ID (Legal Entities)',
  'MICROSOFT.GOVERNMENT.MALAYSIA.IDENTITY_CARD_NUMBER': 'Malaysia Identity Card (MyKad)',
  'MICROSOFT.GOVERNMENT.MALTA.DRIVERS.LICENSE.NUMBER': 'Malta Driver\'s License',
  'MICROSOFT.GOVERNMENT.MALTA.IDENTITY.CARD.NUMBER': 'Malta Identity Card',
  'MICROSOFT.GOVERNMENT.MALTA.PASSPORT.NUMBER': 'Malta Passport Number',
  'MICROSOFT.GOVERNMENT.MALTA.TAX.ID.NUMBER': 'Malta Tax ID',
  'MICROSOFT.GOVERNMENT.NETHERLANDS.BSN_NUMBER': 'Netherlands Citizen Service Number (BSN)',
  'MICROSOFT.GOVERNMENT.NETHERLANDS.DRIVERS.LICENSE.NUMBER': 'Netherlands Driver\'s License',
  'MICROSOFT.GOVERNMENT.NETHERLANDS.PASSPORT.NUMBER': 'Netherlands Passport Number',
  'MICROSOFT.GOVERNMENT.NETHERLANDS.TAX.IDENTIFICATION.NUMBER': 'Netherlands Tax ID',
  'MICROSOFT.GOVERNMENT.NETHERLANDS.VALUE.ADDED.TAX.NUMBER': 'Netherlands VAT Number',
  'MICROSOFT.GOVERNMENT.NEW.ZEALAND.INLAND.REVENUE.NUMBER': 'New Zealand IRD Number',
  'MICROSOFT.GOVERNMENT.NEWZEALAND.DRIVER.LICENSE': 'New Zealand Driver\'s License',
  'MICROSOFT.GOVERNMENT.NEWZEALAND.MINISTRY_OF_HEALTH_NUMBER': 'New Zealand Health Number (NHI)',
  'MICROSOFT.GOVERNMENT.NEWZEALAND.SOCIAL.WELFARE.NUMBER': 'New Zealand Social Welfare Number',
  'MICROSOFT.GOVERNMENT.NORWAY.IDENTIFICATION_NUMBER': 'Norway National ID (Fødselsnummer)',
  'MICROSOFT.GOVERNMENT.PHILIPPINES.UNIFIED_MULTIPURPOSE_ID_NUMBER': 'Philippines Unified Multi-Purpose ID (UMID)',
  'MICROSOFT.GOVERNMENT.POLAND.DRIVERS.LICENSE.NUMBER': 'Poland Driver\'s License',
  'MICROSOFT.GOVERNMENT.POLAND.IDENTITY_CARD': 'Poland Identity Card (Dowód Osobisty)',
  'MICROSOFT.GOVERNMENT.POLAND.PASSPORT_NUMBER': 'Poland Passport Number',
  'MICROSOFT.GOVERNMENT.POLAND.PESEL_NUMBER': 'Poland PESEL Number',
  'MICROSOFT.GOVERNMENT.POLAND.TAX.IDENTIFICATION.NUMBER': 'Poland Tax ID (NIP)',
  'MICROSOFT.GOVERNMENT.POLISH.REGON.NUMBER': 'Poland REGON Number',
  'MICROSOFT.GOVERNMENT.PORTUGAL.CITIZEN_CARD_NUMBER': 'Portugal Citizen Card',
  'MICROSOFT.GOVERNMENT.PORTUGAL.DRIVERS.LICENSE.NUMBER': 'Portugal Driver\'s License',
  'MICROSOFT.GOVERNMENT.PORTUGAL.PASSPORT.NUMBER': 'Portugal Passport Number',
  'MICROSOFT.GOVERNMENT.PORTUGAL.TAX.IDENTIFICATION.NUMBER': 'Portugal Tax ID (NIF)',
  'MICROSOFT.GOVERNMENT.ROMANIA.DRIVERS.LICENSE.NUMBER': 'Romania Driver\'s License',
  'MICROSOFT.GOVERNMENT.ROMANIA.PASSPORT.NUMBER': 'Romania Passport Number',
  'MICROSOFT.GOVERNMENT.ROMANIA.PERSONAL.NUMERICAL.CODE': 'Romania Personal Numerical Code (CNP)',
  'MICROSOFT.GOVERNMENT.RUSSIAN.PASSPORT.NUMBER.DOMESTIC': 'Russia Domestic Passport',
  'MICROSOFT.GOVERNMENT.RUSSIAN.PASSPORT.NUMBER.INTERNATIONAL': 'Russia International Passport',
  'MICROSOFT.GOVERNMENT.SAUDIARABIA.NATIONAL_ID_NUMBER': 'Saudi Arabia National ID',
  'MICROSOFT.GOVERNMENT.SINGAPORE.NATIONAL_REGISTRATION_IDENTITY_CARD_NUMBER': 'Singapore NRIC',
  'MICROSOFT.GOVERNMENT.SLOVAKIA.DRIVERS.LICENSE.NUMBER': 'Slovakia Driver\'s License',
  'MICROSOFT.GOVERNMENT.SLOVAKIA.PASSPORT.NUMBER': 'Slovakia Passport Number',
  'MICROSOFT.GOVERNMENT.SLOVAKIA.PERSONAL.NUMBER': 'Slovakia Personal Number',
  'MICROSOFT.GOVERNMENT.SLOVENIA.DRIVERS.LICENSE.NUMBER': 'Slovenia Driver\'s License',
  'MICROSOFT.GOVERNMENT.SLOVENIA.PASSPORT.NUMBER': 'Slovenia Passport Number',
  'MICROSOFT.GOVERNMENT.SLOVENIA.TAX.IDENTIFICATION.NUMBER': 'Slovenia Tax ID',
  'MICROSOFT.GOVERNMENT.SLOVENIA.UNIQUE.MASTER.CITIZEN.NUMBER': 'Slovenia Unique Master Citizen Number (EMŠO)',
  'MICROSOFT.GOVERNMENT.SOUTHAFRICA.IDENTIFICATION_NUMBER': 'South Africa ID Number',
  'MICROSOFT.GOVERNMENT.SOUTHKOREA.RESIDENT_REGISTRATION_NUMBER': 'South Korea Resident Registration Number',
  'MICROSOFT.GOVERNMENT.SPAIN.DNI': 'Spain National ID (DNI)',
  'MICROSOFT.GOVERNMENT.SPAIN.DRIVERS.LICENSE.NUMBER': 'Spain Driver\'s License',
  'MICROSOFT.GOVERNMENT.SPAIN.PASSPORT.NUMBER': 'Spain Passport Number',
  'MICROSOFT.GOVERNMENT.SPAIN.SOCIAL_SECURITY_NUMBER': 'Spain Social Security Number',
  'MICROSOFT.GOVERNMENT.SPAIN.TAX.IDENTIFICATION.NUMBER': 'Spain Tax ID (NIF)',
  'MICROSOFT.GOVERNMENT.SWEDEN.DRIVERS.LICENSE.NUMBER': 'Sweden Driver\'s License',
  'MICROSOFT.GOVERNMENT.SWEDEN.NATIONAL_ID_NUMBER': 'Sweden Personal ID (Personnummer)',
  'MICROSOFT.GOVERNMENT.SWEDEN.PASSPORT_NUMBER': 'Sweden Passport Number',
  'MICROSOFT.GOVERNMENT.SWEDEN.TAX.IDENTIFICATION.NUMBER': 'Sweden Tax ID',
  'MICROSOFT.GOVERNMENT.SWISS.SSN.AHV.NUMBER': 'Switzerland Social Security Number (AHV)',
  'MICROSOFT.GOVERNMENT.TAIWAN.NATIONAL_ID_NUMBER': 'Taiwan National ID',
  'MICROSOFT.GOVERNMENT.TAIWAN.PASSPORT_NUMBER': 'Taiwan Passport Number',
  'MICROSOFT.GOVERNMENT.TAIWAN.RESIDENT_CERTIFICATE': 'Taiwan Resident Certificate (ARC)',
  'MICROSOFT.GOVERNMENT.THAILAND.THAI_POPULATION_IDENTIFICATION_CODE': 'Thailand Population ID',
  'MICROSOFT.GOVERNMENT.TURKEY.TURKISH_NATIONAL_IDENTIFICATION_NUMBER': 'Turkey National ID (TC Kimlik No)',
  'MICROSOFT.GOVERNMENT.U.K..UNIQUE.TAXPAYER.REFERENCE.NUMBER': 'UK Unique Taxpayer Reference (UTR)',
  'MICROSOFT.GOVERNMENT.UK.DRIVERS_LICENSE_NUMBER': 'UK Driver\'s License',
  'MICROSOFT.GOVERNMENT.UK.ELECTORAL_ROLL_NUMBER': 'UK Electoral Roll Number',
  'MICROSOFT.GOVERNMENT.UK.NATIONAL_HEALTH_SERVICE_NUMBER': 'UK NHS Number',
  'MICROSOFT.GOVERNMENT.UK.NATIONAL_INSURANCE_NUMBER': 'UK National Insurance Number',
  'MICROSOFT.GOVERNMENT.UK.PASSPORT_NUMBER': 'UK Passport Number',
  'MICROSOFT.GOVERNMENT.UKRAINE.PASSPORT.DOMESTIC': 'Ukraine Domestic Passport',
  'MICROSOFT.GOVERNMENT.UKRAINE.PASSPORT.INTERNATIONAL': 'Ukraine International Passport',
  'MICROSOFT.GOVERNMENT.US.DRIVERS_LICENSE_NUMBER': 'US Driver\'s License',
  'MICROSOFT.GOVERNMENT.US.DRUG_ENFORCEMENT_AGENCY_NUMBER': 'US DEA Number',
  'MICROSOFT.GOVERNMENT.US.INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER': 'US Individual Taxpayer ID (ITIN)',
  'MICROSOFT.GOVERNMENT.US.PASSPORT_NUMBER': 'US Passport Number',
  'MICROSOFT.GOVERNMENT.US.SOCIAL_SECURITY_NUMBER': 'US Social Security Number (SSN)',
  'MICROSOFT.GOVERNMENT.US.STATE': 'US State',
  'MICROSOFT.GOVERNMENT.US.ZIP_CODE': 'US ZIP Code',
  'MICROSOFT.MISCELLANEOUS.IPADDRESS': 'IP Address',
  'MICROSOFT.PERSONAL.AGE': 'Age',
  'MICROSOFT.PERSONAL.DATE_OF_BIRTH': 'Date of Birth',
  'MICROSOFT.PERSONAL.EMAIL': 'Email Address',
  'MICROSOFT.PERSONAL.ETHNIC_GROUP': 'Ethnic Group',
  'MICROSOFT.PERSONAL.EU.GPS_COORDINATES': 'EU GPS Coordinates',
  'MICROSOFT.PERSONAL.EU.MOBILE_PHONE_NUMBER': 'EU Mobile Phone Number',
  'MICROSOFT.PERSONAL.EU.PHONE_NUMBER': 'EU Phone Number',
  'MICROSOFT.PERSONAL.GENDER': 'Gender',
  'MICROSOFT.PERSONAL.GEOLOCATION': 'Geolocation',
  'MICROSOFT.PERSONAL.IPADDRESS': 'IP Address',
  'MICROSOFT.PERSONAL.JAPANESE.MY.NUMBER.CORPORATE': 'Japan Corporate My Number',
  'MICROSOFT.PERSONAL.JAPANESE.MY.NUMBER.PERSONAL': 'Japan Personal My Number',
  'MICROSOFT.PERSONAL.NAME': 'Name',
  'MICROSOFT.PERSONAL.PHYSICALADDRESS': 'Physical Address',
  'MICROSOFT.PERSONAL.US.PHONE_NUMBER': 'US Phone Number',
  'MICROSOFT.SECURITY.COMMON_PASSWORDS': 'Common Passwords'
};

/**
 * Converts a technical classification name to a friendly display name
 * @param classificationName - The technical classification name (e.g., "MICROSOFT.PERSONAL.EMAIL")
 * @returns The friendly display name (e.g., "EMAIL") - removes first two segments (MICROSOFT.CATEGORY)
 */
export function getClassificationDisplayName(classificationName: string): string {
  try {
    if (!classificationName) return '';
    
    // Remove first two segments (e.g., MICROSOFT.PERSONAL or MICROSOFT.GOVERNMENT)
    const segments = classificationName.split('.');
    if (segments.length > 2) {
      return segments.slice(2).join('.');
    }
    
    // If only 2 or fewer segments, return the last one
    return segments[segments.length - 1] || classificationName;
    
  } catch (error) {
    console.error('Error formatting classification name:', error);
    return classificationName || '';
  }
}

/**
 * Converts an array of technical classification names to display names
 * @param classificationNames - Array of technical classification names
 * @returns Array of friendly display names
 */
export function getClassificationDisplayNames(classificationNames: string[]): string[] {
  try {
    if (!Array.isArray(classificationNames)) {
      return [];
    }
    return classificationNames.map(name => getClassificationDisplayName(name));
  } catch (error) {
    console.error('Error formatting classification names:', error);
    return classificationNames || [];
  }
}

/**
 * Finds the technical classification name from a display name
 * @param displayName - The friendly display name (e.g., "Personal.Email")
 * @returns The technical classification name with MICROSOFT prefix
 */
export function getClassificationTechnicalName(displayName: string): string {
  try {
    // If doesn't have MICROSOFT prefix, add it back
    if (displayName && !displayName.startsWith('MICROSOFT.')) {
      return 'MICROSOFT.' + displayName;
    }
    
    return displayName || '';
  } catch (error) {
    console.error('Error getting technical classification name:', error);
    return displayName || '';
  }
}
